# Generated by Django 4.2.3 on 2023-08-09 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_item_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='photo',
        ),
    ]
