# Generated by Django 4.2.3 on 2023-08-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_item_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='photo',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
