# Generated by Django 4.2.3 on 2023-08-09 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_item_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='photo',
            new_name='image',
        ),
    ]
